-- BDS Room 6 was imported one month late. The confirmed occupancy date is
-- 01/07/2025; the legal term records remain separate from this billing repair.
update public.tenancies as tenancy
set
  check_in_date = date '2025-07-01',
  tenancy_start_date = case
    when tenancy.tenancy_start_date is null
      or tenancy.tenancy_start_date = date '2025-08-01'
      then date '2025-07-01'
    else tenancy.tenancy_start_date
  end,
  start_date = case
    when tenancy.start_date = date '2025-08-01'
      then date '2025-07-01'
    else tenancy.start_date
  end,
  rent_due_day = 1,
  due_day = 1,
  updated_at = now()
from public.properties as property,
  public.rooms as room
where property.id = tenancy.property_id
  and room.id = tenancy.room_id
  and (
    upper(coalesce(property.property_code, '')) = 'BDS'
    or upper(property.name) like 'BDS%'
  )
  and regexp_replace(
    coalesce(room.room_number, room.name, ''),
    '[^0-9]',
    '',
    'g'
  ) = '6'
  and coalesce(
    tenancy.check_in_date,
    tenancy.tenancy_start_date,
    tenancy.contract_start,
    tenancy.start_date
  ) = date '2025-08-01';

-- Add a check-in-month invoice for every canonical tenancy that does not
-- already have one. The earliest existing bill preserves the historical rent
-- for renewed tenancies whose current rent has changed.
with tenancy_first_invoices as (
  select
    tenancy.id as tenancy_id,
    tenancy.organization_id,
    tenancy.property_id,
    tenancy.unit_id,
    tenancy.room_id,
    tenant.profile_id as portal_profile_id,
    tenant_record.id as tenant_record_id,
    coalesce(
      tenancy.check_in_date,
      tenancy.tenancy_start_date,
      tenancy.contract_start,
      tenancy.start_date
    ) as first_invoice_date,
    greatest(coalesce(tenancy.deposit, 0), 0) as deposit_amount,
    greatest(
      coalesce(
        (
          select existing.amount
          from public.rent_bills existing
          where existing.tenancy_id = tenancy.id
            and existing.status::text not in ('cancelled', 'voided')
          order by existing.bill_month, existing.created_at
          limit 1
        ),
        nullif(tenancy.monthly_rental, 0),
        nullif(tenancy.monthly_rent, 0),
        0
      ),
      0
    ) as monthly_rent
  from public.tenancies tenancy
  left join public.tenants tenant
    on tenant.id = tenancy.tenant_id
  left join lateral (
    select record.id
    from public.tenant_records record
    where record.tenancy_id = tenancy.id
    order by record.updated_at desc nulls last, record.created_at desc
    limit 1
  ) tenant_record on true
  where coalesce(
      tenancy.check_in_date,
      tenancy.tenancy_start_date,
      tenancy.contract_start,
      tenancy.start_date
    ) is not null
    and coalesce(
      tenancy.check_in_date,
      tenancy.tenancy_start_date,
      tenancy.contract_start,
      tenancy.start_date
    ) <= current_date
    and tenancy.status::text <> 'cancelled'
)
insert into public.rent_bills (
  organization_id,
  tenancy_id,
  tenant_id,
  tenant_record_id,
  property_id,
  unit_id,
  room_id,
  bill_month,
  due_date,
  invoice_date,
  amount,
  deposit_amount,
  paid_amount,
  status,
  invoice_source,
  notes,
  created_by
)
select
  first_invoice.organization_id,
  first_invoice.tenancy_id,
  first_invoice.portal_profile_id,
  first_invoice.tenant_record_id,
  first_invoice.property_id,
  first_invoice.unit_id,
  first_invoice.room_id,
  date_trunc('month', first_invoice.first_invoice_date)::date,
  first_invoice.first_invoice_date,
  first_invoice.first_invoice_date,
  first_invoice.monthly_rent,
  first_invoice.deposit_amount,
  0,
  'unpaid',
  'automatic',
  'Historical check-in-month invoice generated by billing correction.',
  null
from tenancy_first_invoices first_invoice
where first_invoice.property_id is not null
  and first_invoice.room_id is not null
  and not exists (
    select 1
    from public.rent_bills existing
    where existing.tenancy_id = first_invoice.tenancy_id
      and existing.bill_month =
        date_trunc('month', first_invoice.first_invoice_date)::date
  )
on conflict (tenancy_id, bill_month) do nothing;

-- Apply the same correction to imported tenants that have not yet been
-- converted into canonical tenancy rows.
with imported_first_invoices as (
  select
    record.id as tenant_record_id,
    record.property_id,
    record.unit_id,
    record.room_id,
    record.contract_start as first_invoice_date,
    greatest(coalesce(record.deposit, 0), 0) as deposit_amount,
    greatest(
      coalesce(
        (
          select existing.amount
          from public.rent_bills existing
          where existing.tenant_record_id = record.id
            and existing.tenancy_id is null
            and existing.status::text not in ('cancelled', 'voided')
          order by existing.bill_month, existing.created_at
          limit 1
        ),
        nullif(record.monthly_rent, 0),
        0
      ),
      0
    ) as monthly_rent
  from public.tenant_records record
  where record.tenancy_id is null
    and record.property_id is not null
    and record.room_id is not null
    and record.contract_start is not null
    and record.contract_start <= current_date
    and nullif(btrim(record.full_name), '') is not null
    and lower(record.status) not in ('cancelled', 'vacant')
)
insert into public.rent_bills (
  organization_id,
  tenancy_id,
  tenant_id,
  tenant_record_id,
  property_id,
  unit_id,
  room_id,
  bill_month,
  due_date,
  invoice_date,
  amount,
  deposit_amount,
  paid_amount,
  status,
  invoice_source,
  notes,
  created_by
)
select
  null,
  null,
  null,
  first_invoice.tenant_record_id,
  first_invoice.property_id,
  first_invoice.unit_id,
  first_invoice.room_id,
  date_trunc('month', first_invoice.first_invoice_date)::date,
  first_invoice.first_invoice_date,
  first_invoice.first_invoice_date,
  first_invoice.monthly_rent,
  first_invoice.deposit_amount,
  0,
  'unpaid',
  'automatic',
  'Historical check-in-month invoice generated by billing correction.',
  null
from imported_first_invoices first_invoice
where not exists (
  select 1
  from public.rent_bills existing
  where existing.tenant_record_id = first_invoice.tenant_record_id
    and existing.tenancy_id is null
    and existing.bill_month =
      date_trunc('month', first_invoice.first_invoice_date)::date
)
on conflict (tenant_record_id, bill_month)
where tenant_record_id is not null
do nothing;

-- Keep the check-in invoice metadata aligned without changing rent amounts,
-- payment status, paid amounts, or payment transaction history.
with invoice_terms as (
  select
    tenancy.id as tenancy_id,
    coalesce(
      tenancy.check_in_date,
      tenancy.tenancy_start_date,
      tenancy.contract_start,
      tenancy.start_date
    ) as first_invoice_date,
    greatest(coalesce(tenancy.deposit, 0), 0) as deposit_amount
  from public.tenancies tenancy
)
update public.rent_bills bill
set
  deposit_amount = term.deposit_amount,
  due_date = term.first_invoice_date,
  invoice_date = term.first_invoice_date,
  retain_until = greatest(
    bill.retain_until,
    (term.first_invoice_date + interval '7 years')::date
  ),
  updated_at = now()
from invoice_terms term
where bill.tenancy_id = term.tenancy_id
  and term.first_invoice_date is not null
  and bill.status::text not in ('cancelled', 'voided')
  and bill.bill_month = date_trunc('month', term.first_invoice_date)::date;

with invoice_terms as (
  select
    record.id as tenant_record_id,
    record.contract_start as first_invoice_date,
    greatest(coalesce(record.deposit, 0), 0) as deposit_amount
  from public.tenant_records record
  where record.tenancy_id is null
    and record.contract_start is not null
)
update public.rent_bills bill
set
  deposit_amount = term.deposit_amount,
  due_date = term.first_invoice_date,
  invoice_date = term.first_invoice_date,
  retain_until = greatest(
    bill.retain_until,
    (term.first_invoice_date + interval '7 years')::date
  ),
  updated_at = now()
from invoice_terms term
where bill.tenancy_id is null
  and bill.tenant_record_id = term.tenant_record_id
  and bill.status::text not in ('cancelled', 'voided')
  and bill.bill_month = date_trunc('month', term.first_invoice_date)::date;

-- Deposit belongs only on the check-in-month invoice. Clear a misplaced
-- deposit only when no money has been recorded against that invoice.
with invoice_terms as (
  select
    tenancy.id as tenancy_id,
    date_trunc(
      'month',
      coalesce(
        tenancy.check_in_date,
        tenancy.tenancy_start_date,
        tenancy.contract_start,
        tenancy.start_date
      )
    )::date as first_bill_month
  from public.tenancies tenancy
)
update public.rent_bills bill
set
  deposit_amount = 0,
  updated_at = now()
from invoice_terms term
where bill.tenancy_id = term.tenancy_id
  and bill.bill_month <> term.first_bill_month
  and bill.deposit_amount > 0
  and bill.paid_amount = 0
  and bill.status::text not in ('paid', 'verified', 'confirmed', 'cancelled', 'voided');
